version: '3.4'

services:

    jekyll:
        image: jekyll/jekyll
        command: jekyll serve --force_polling --watch
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll